### PR TITLE
Adding tests for openjdk 13

### PR DESCRIPTION
**Pull request by shen-tian**
Clojure adding official images for openjdk13 and 14 EA, so adding java 13 tests.

### CODE REVIEW

**Comment by bbatsov** [comment]
I thought the latest version is 13. :-)

**Comment by shen-tian** [comment]
Didn't mean to open the PR, but might as well now: Clojure (and thus CircleCI) does provide 13 and 14-ea OpenJDK images now.

Guess the question is, do we want to add another 5 builds into the CI matrix?

**Comment by bbatsov** [comment]
I guess it makes sense to test on all supported versions which are currently 8, 11 and 13. Once 14 is out we'll replace 14 with it.

**Comment by shen-tian** [comment]
Ok. Looks easy enough. I'll re-open the PR on that basis.

**Comment by bbatsov** [comment]
Just remembered we even had some documentation about this - https://nrepl.org/nrepl/about/compatibility.html

**Comment by shen-tian** [comment]
I was looking for that. Thanks. FWIW, the tests run fine on Java 14 EA.

**Comment by shen-tian** [comment]
@bbatsov: pretty straightforward. We'll move from 13 -> 14 when the time comes.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
