### PR TITLE
Logo (closes #30)

### LINKED ISSUE #30: Create a simple logo for the project (and this org)
The GitHub org is looking a bit pale without a logo. :-) It'd be nice if the project had some basic logo, but I'll need some help with that, as I'm a complete zero in the design department. :-)

### PR DESCRIPTION
**Pull request by tonsky**

### CODE REVIEW

**Comment by bbatsov** [comment]
🙇 🙇 🙇 

Спасибо большое, Никита!

**Comment by tonsky** [comment]
Happy to help :)

**Comment by bbatsov** [comment]
@tonsky Btw, can you also submit the AI/PSD/whatever is the source of the logo for archive purposes? It'd be nice to have it if we have to cut other variations of the logo out of it.

**Comment by tonsky** [comment]
It’s in Figma https://www.figma.com/file/SOZ4YzGljrXDFMKhQ0J0Uml1/nREPL-logo

**Comment by bbatsov** [comment]
Thanks! Btw, would it be possible to also make one square version of the logo like https://github.com/rubocop-hq/rubocop/blob/master/logo/rubo-logo-square.png?

**Pull request merged**
