### PR TITLE
ISSUE-203-fix

### PR DESCRIPTION
**Pull request by pradeepbishnoi**
Before submitting a PR make sure the following things have been done:

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ ] You've added tests to cover your change(s)
- [ ] All tests are passing
- [ ] The new code is not generating reflection warnings
- [ ] You've updated the [changelog](../CHANGELOG.md)(that only applies to user-visible changes)

Thanks!

*If you're just starting out to hack on nREPL you might find this [section of its
manual][1] extremely useful.*

[1]: https:/nrepl.org/nrepl/hacking_on_nrepl.html

### CODE REVIEW

**Comment by SevereOverfl0w** [comment]
Spaces are valid when not using deps.edn.

**Comment by bbatsov** [comment]
Probably that should be some note in the docs, instead of being part of the cmdline help (mostly because adding meaningful explanations will require some space).

**Comment by pradeepbishnoi** [comment]
Thanks @SevereOverfl0w  @bbatsov for input. How about adding a small note (screenshot below) and removing the text from cmdline help.

image

**Comment by SevereOverfl0w** [comment]
I think the note should explicitly mention deps.edn, as that's where the limitation is.

**Comment by bbatsov** [comment]
Agreed. I guess the note can include some exaples directly for the sake of clarity (AsciiDoc admonitions are quite powerful).

**Comment by pradeepbishnoi** [comment]
@SevereOverfl0w @bbatsov now i think it should be good to merge.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
