### PR TITLE
Add nREPL client support for unix domain sockets

### PR DESCRIPTION
**Pull request by vincentjames501**
Before I write some tests, is this useful at all?

Before submitting a PR make sure the following things have been done:

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests to cover your change(s)
- [x] All tests are passing
- [x] The new code is not generating reflection warnings
- [x] You've updated the [changelog](../CHANGELOG.md)(that only applies to user-visible changes)

Thanks!

### CODE REVIEW

**Comment by bbatsov** [comment]
Yeah, I think that's quite useful. Ideally the built-in client should work will all bundled transports.

**Comment by vincentjames501** [comment]
@bbatsov I think it's ready.

**Comment by bbatsov** [comment]
@vincentjames501 Your changes look great to me. Just mention some example usage in the docs as well (e.g. here https://nrepl.org/nrepl/0.9/usage/clients.html#using-the-built-in-client).

**Comment by vincentjames501** [comment]
@bbatsov , done.

**Comment by bbatsov** [comment]
Thanks for tackling this!

**Pull request merged**
