### PR TITLE
Add :read-cond option for `eval`.

### PR DESCRIPTION
**Pull request by FiV0**
Allow to pass reader-conditional options, so that reader
conditionals can be processed in higher middlerware layers.

Before submitting a PR make sure the following things have been done:

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests to cover your change(s)
- [ ] All tests are passing (No a bencode one fails)
- [x] The new code is not generating reflection warnings
- [x] You've updated the [changelog](../CHANGELOG.md)(that only applies to user-visible changes)

### CODE REVIEW

**Comment by FiV0** [comment]
So this is half of the fix for https://github.com/clojure-emacs/cider-nrepl/issues/437.

One test fails for the Bencode Transport layer with "Syntax error reading source at (REPL:1:3).\nConditional read not allowed\n". I don't know why that is the case. Maybe you can give me a pointer.

**Comment by bbatsov** [comment]
Where is this failure exactly? I opened some of the failed builds and I see the only test failing is the one added in the PR? I'm guessing the error you got originated somewhere in `clojure.repl`, so it's probably best to check the code there which generated it.

**Comment by shen-tian** [comment]
I'm guessing the bencode transport stringizes keywords in value slots, including `:preserve`. If I try to run this line in a REPL, I get the "Conditional read not allowed" error:

```
(read-string {:read-cond "preserve"} "#?(:clj (Math/random))")
```

So try this:

1. Either decide to send it as a string, and keywordize in `interruptable-eval` OR

2. modify this fn: to noramalize anything in `:read-cond` slot to keyword?

https://github.com/nrepl/nrepl/blob/151102df3088f7da6702bd162fc56af99dd7c5e6/src/clojure/nrepl/server.clj#L23-L29

I'd suggest the first option, as we typically don't use keywords as values in other requests, and it keeps the logic concentrated.

**Comment by shen-tian** [comment]
I'm guessing the bencode transport stringizes keywords in value slots, including `:preserve`. If I try to run this line in a REPL, I get the "Conditional read not allowed" error:

```
(read-string {:read-cond "preserve"} "#?(:clj (Math/random))")
```

So try this:

1. Either decide to send it as a string, and keywordize in `interruptable-eval` OR

2. modify this fn: to noramalize anything in `:read-cond` slot to keyword?

https://github.com/nrepl/nrepl/blob/151102df3088f7da6702bd162fc56af99dd7c5e6/src/clojure/nrepl/server.clj#L23-L29

I'd suggest the first option, as we typically don't use keywords as values in other requests, and it keeps the logic concentrated.

**Comment by bbatsov** [comment]
@FiV0 ping :-)

**Comment by FiV0** [comment]
Seen the reply. Will look at this on the weekend.

**Comment by bbatsov** [comment]
@FiV0 Just in time. :-) Seems we're one small code style fix from merging this. I'll probably cut the new nREPL tomorrow.

**Pull request merged**
