### PR TITLE
Add constant DCL across evalutions

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
This allows for modifications to that classloader which persist across
evaluations.

Testing can be performed like so:

```
❯ clj -Sdeps '{:deps {nrepl {:mvn/version "0.4.2-SNAPSHOT"} org.clojure/tools.deps.alpha
                {:git/url "https://github.com/clojure/tools.deps.alpha.git"
                 :sha "d492e97259c013ba401c5238842cd3445839d020"}}}' -m nrepl.cmdline --interactive
network-repl
Clojure 1.9.0
user=> (use 'clojure.tools.deps.alpha.repl)
nil
user=>  (add-lib 'org.clojure/core.memoize {:mvn/version "0.7.1"})
true
user=> (require 'clojure.core.memoize)
nil
user=>
```

### CODE REVIEW

**Comment by bbatsov** [comment]
Is this working with any released version `tools.deps` as well? I noticed you've used some git snapshot in your example.

**Comment by SevereOverfl0w** [comment]
add-lib is an alpha functionality, I used the exact values from Alex Miller's blog on the topic: http://insideclojure.org/2018/05/04/add-lib/

I've just tested with pomegranate too:

```
❯ clj -Sdeps '{:deps {nrepl {:mvn/version "0.4.2-SNAPSHOT"} com.cemerick/pomegranate {:mvn/version "1.0.0"}}}' -m nrepl.cmdline --interactive
network-repl
Clojure 1.9.0
user=> (use '[cemerick.pomegranate :only (add-dependencies)])
nil
user=> cemerick.pomegranate.aether/maven-central
{"central" "https://repo1.maven.org/maven2/"}
(add-dependencies :coordinates '[[org.clojure/core.memoize "0.7.1"]] :repositories (merge cemerick.pomegranate.aether/maven-central
                                          {"clojars" "https://clojars.org/repo"}))
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map "0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure "1.6.0"] nil}
user=> (require 'clojure.core.memoize)
nil
```

**Comment by bbatsov** [comment]
Hmm, seems to work just fine.

**Comment by bbatsov** [comment]
I'll cut a 0.4.2 is a bit, so more people can benefit from this.

**Pull request merged**
