### PR TITLE
Remove duplicate ids.

### PR DESCRIPTION
**Pull request by th994**
Before submitting a PR make sure the following things have been done:

- [ ] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ ] You've added tests to cover your change(s)
- [x] All tests are passing
- [x] The new code is not generating reflection warnings
- [ ] You've updated the [changelog](../CHANGELOG.md)(that only applies to user-visible changes)

Thanks!

*If you're just starting out to hack on nREPL you might find this [section of its
manual][1] extremely useful.*

[1]: https:/nrepl.org/nrepl/hacking_on_nrepl.html

### CODE REVIEW

**Comment by th994** [comment]
Since the following code in delimited-transport-seq merges the id, there is no need to create a new message with the id.

```
#(merge % delimited-slots)
```

I'm sorry if this is a misunderstanding.

**Comment by bbatsov** [comment]
I see that tests are passing, so most likely you're right. How did you notice this?

**Comment by th994** [comment]
Thanks for the confirmation.

I'm curious about the behavior of nrepl and noticed it while reading the code from scratch.

There was no problem with the operation.

**Comment by bbatsov** [comment]
Thanks!

**Comment by bbatsov** [comment]
Hmm, after merging it I realized that now this doesn't quite work like the description of the function, so probably this has to be updated as well. (the description explicitly mentions adding the id to the message)

**Comment by th994** [comment]
Thanks.

I'll try to fix the description too.
I'm not good at English, so I'd appreciate your suggestions.

**Comment by bbatsov** [comment]
Sure! I guess the most important thing is to make it clear how the a `message` obtains its id. Please, also add a docstring for `delimited-transport-seq`, so it's clearer for casual readers of the code what is its purpose.

**Pull request merged**
